version: '3'
services:
  database:
    container_name: scadabr_mysql
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=scadabr
    expose: ["3306"]
    volumes:
      - ./docker/volumes/databases:/home/
  phpmyadmin:
    container_name: scadabr_phpmyadmin
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
  scadabr:
    container_name: scadabr-ef
    image: kenyos/scadabr-ef:latest
    ports: 
      - "8080:8080"
    depends_on: 
      - database
    expose: ["8080", "8000"]
    links:
      - database:database